### ISSUE TITLE
Loss of circuit network conditions

### ISSUE THREAD

**Issue by dtupper** [demipixel/factorio-generators#10]
When converting this BP: https://gist.github.com/dtupper/db1a268445b8a737fa7f7f9b252f6ffd

using these settings: http://i.imgur.com/s5RJfUc.png

All circuit conditions are lost. The pumps should have circuit conditions for fraction products, but they do not appear in the converted BP.

note: A workaround is to place the original BP, then replace with the "Only include changed entities" BP.

**Comment by demipixel** [comment]
Haven't tested this yet but this should be working now (was an issue with factorio-blueprint).
