### ISSUE TITLE
Error: Y_LENGTH is not defined When generating miner blueprint

### ISSUE THREAD

**Issue by basdejong95** [demipixel/factorio-generators#14]
Hi, using factorio 0.15.15, i get the error : `Error: Y_LENGTH is not defined ` . Can you please fix ?

Kind regards

**Comment by basdejong95** [comment]
Also, when deselecting the option to create a train station, it works fine.

**Comment by demipixel** [comment]
I believe I fixed this a while ago, though feel free to open if you still experience the issue.
