### ISSUE TITLE
Oil: Train output route

### ISSUE THREAD

**Issue by dragonfly8677** [demipixel/factorio-generators#16]
Oil outposts do not provide a train exit route when selecting the "Provide exit route" option. The option does seemingly nothing. It works for normal outposts though, so this issue is specific to oil outposts.

**Comment by demipixel** [comment]
Can you test this again?

**Comment by dragonfly8677** [comment]
I still get the same result. All default settings except that I also add the exit route setting.

Input string: https://pastebin.com/J63WRH0J

Output string: https://pastebin.com/zZBSJhQB

**Comment by bcrotty** [comment]
I have the same issue.

**Comment by demipixel** [comment]
Fixed.
