### ISSUE TITLE
Feature request: on-site smelting to the blueprint with the adequate capacity for the amount of miners placed

### ISSUE THREAD

**Issue by kauron** [demipixel/factorio-generators#19]

**Comment by demipixel** [comment]
I know this is a bit of a popular request, but for now it's really not in the scope of the project. It would continue on to requesting different designs for the furnace arrays (e.g. Regular, bots, with beacons, etc) as well as other changes to the existing development (defenses would have to be redone, routing to the train station would have to redone as well as adding routing to the furnaces, etc).

Maybe if some day someone is extremely bored and decides to go for it (or if we make Autotorio more modularized, so in a sense you could say "Create an ore outpost with an ore array module"), but until then I'm going to close this issue.
