### ISSUE TITLE
Oil Outposts with Fluid Wagons

### ISSUE THREAD

**Issue by bcrotty** [demipixel/factorio-generators#20]
When I change the Fluid Wagon Count to 4, it creates the extra tanks and pumps, but the wall, gate, and turrets are still in the same place as if there were only 2 Fluid Wagons.

**Comment by demipixel** [comment]
Do you have a picture? Are the walls not far out enough? It's possible they're unaffected because the pumpjacks go out far enough.

**Comment by bcrotty** [comment]
It might just be that the whole tank/pump assembly is too far South in this picture. It seems like it would work better further North.

![2017-08-21 22_40_57-factorio 0 15 33](https://user-images.githubusercontent.com/6155964/29547791-df9ffc3e-86c1-11e7-8be1-90731ce984d6.png)

**Comment by bcrotty** [comment]
@demipixel And I did check the provide exit route button on this, but I seem to have the same issue (#16) as @Elyviere.

**Comment by demipixel** [comment]
Could you try it again?

**Comment by demipixel** [comment]
Please reopen if you still encounter this issue.
