### ISSUE TITLE
Hazard concrete does not match train station location

### ISSUE THREAD

**Issue by drakar** [demipixel/factorio-generators#21]
If you select the option to put hazard concrete under your train station it does not match.

**Comment by demipixel** [comment]
What happens instead? Do you have pictures or anything?

**Comment by drakar** [comment]
![capture](https://user-images.githubusercontent.com/773062/30147248-2b728482-9352-11e7-8457-0d53ac0ff468.PNG)

The hazard concrete is in the south end, when the train depot is in the north end.

**Comment by drakar** [comment]
Actually it looks like the whole concrete layer is off center and rotated improperly.

**Comment by demipixel** [comment]
Fixed.
