### ISSUE TITLE
Pump jacks outside the wall

### ISSUE THREAD

**Issue by jziolkowski** [demipixel/factorio-generators#23]
Hey! Happy user here, noticed something weird today.

This is my pump jacks + single track BP string:

0eNqV1EtugzAQBuC7zNqJMGDzuEpVVYRYqVswCExVhHz3GhJHlcLiZwVG448Bz8xCl2ZS/aCNpXIhXXdmpPJtoVHfTNWsz+zcKypJW9USI1O166qf2v6rqr/JMdLmqn6p5O6dkTJWW63uxraYP8zUXtTgA153M+q70W/ozPomj5x4dBaM5vUuPwuvX/Wg6ntE7NgLGgMof5ISIZODeXIETZ/oaIdK3z7tyV+anWTTBxu5HUYguSUhNehzJUJmgUwRMkPIOJAJQubQoQQzQsgCIcMxQ4fMI4AMooBEpGnyQyLSMaGCCi/uGUiLyIcBtTFPD4gcqhgO9YoIJvbz5JHK3ptgfkZuk7T8N3gZ/ahh3AJknsVRKoosk879AQDszsg=

and settings url:

http://autotorio.com/oil?modded=false&trainSide=Right&trainDirection=Top&module=None&includeRadar=true&turretType=Laser%20Turrets&turretSpacing=6&walls=true&wallThickness=2&includeTrainStation=true&exitRoute=true&concrete=None&borderConcrete=None&trackConcrete=None

The result is here:

0eJy9nVtz20YWhP+Kiy95EVKYwRlc/Af2MXnfSqVoi6UwoUgWRWXX5dJ/XyoWBiAhCH1mp89THF/kdnP0oefSg++rL7vnzfG03Z9Xn7+vtl8P+6fV539/Xz1tH/br3evPnb8dN6vPq+1587i6W+3Xj6//d3x+PP65/vrX6uVutd3fb/67+uxe7lL+mH/57W612Z+35+3mx199+3vvVsfD0+WXD/vXr3v5I4WTn8Pd6tvrj8qfw+Vr3W9Pm68/foe/i3/1/vh8vvzpy79p/+NXL1//+8s/P3E+HXa/f9n8sf57ezj9+Nl/NHz7ff/8+GVzevvnLEvxvZKWJcRjQgZPKpaSClPSvAlxLB0COuLehNAMCZiQ+k2HsHTUoCG9ENpYbTAh/VDtWDpaTEfVj1TaCOkgIULX4UrMkbJX0twqKXMpwcDac/V1zJIswcDaC/E0nDmQq12vhDdKQLL2HPG8D2eM1sfN/fb5sdjsLl/ntP1aHA+7zXt4i8/i1x9d65Jcumq9rnI+rGST1fw/dgWarFYvK/SqeGZ1elXdXKbJJcqXCZ9g/9yYfBtmU+X0qvphNXmCZBPlE6zqPz/eB1ipVdV8UaIWFZ2ahMRsohLY3sw+hbOpSiB7//3nJ8k+m6qrRL09Ljz3eO60Kh00dvtOo2Myv8gloyo1MmjfSZUDZDi+DA/IKPkyKo0M2uOpEo0M2qO7ChoZtAhY1csyOr4KAKNRBQ3mFQDRqGIyycumAkBoVEGbSAlA0KiC9lgTAKDCVwHwU+jTIgHw2avgiQDgKey5mADojNGPJgIAZy+CxgoBuNmLoGFTAGz2ImhPEAGoSZ+OBwCaFV0EwExPF4FETroIJHCyV0MCQMySPiEKADL5M4AAMJM/AQgANPn5PyAzdr4KAJuerqIGuMlfDa8V4ORNQmqAnJ4+CakBdFZ8FQA7K/pUqFbETaIKgJ3OYHgiC56OLwOhZ8mXAeAzsOdkjWKqThueDQDPjh34GiR1CjvxNQA7O7oIAJ09LWh5r0HWOOkiEHD2Sxa87w9F6CSqALAZVdDWbxqAmlEFDZstgM1eBW1e1iI7RHQRy9is6UOzXaZmFEELnO0yNaMIWqhol6kZRdAmQ+0yNQNfxDI0hS9imZlRBC3ZtMvIjCJomaJbJmYUQXucd8vErPgilokZRdCw3QE50/NVKIIm75u0UyRNogpN1KQ9Pzpkik5/lHbL2Cz5H4gmafKO2ZY4OD3vWG25TE6h48KVwBw9nibknRMvAXjWBjIAekYZtAmZKwF81gYjFOBnMJCh2FVnygAm65WBDMUWEVGGA6br8UPhodwBE/bKQMYtRYvzoXg4HZ739/OzxcnEIFsbyN3S9CM58Yk70VNn03OL1Q/1zHfZ8pXqbgGLCaJNYJy7Re2HgqrZR1A+h26hiwmipWjnbvH7oSA3m5zyDepbEH8kaH7il6+feUvkDw2KvTFeT9PfsvlDQe2soGyfmNdQOjpEbNSqMN3O6cnnjwrTbva5kc8gFaZdRX+QeRWm+11FXu6Y9J0gPZNFhmxPjave0/m03u6Lp/PhONXi5O0RzzJmDOenVyUPf5yLy39272ip39WSzZSr9hOoRVhanF6LZ2nxei0lS0ul1tKypIhaCm3kBrUU2sCt1VJo47ZRS6EN21YtpaDZokduwRotokduwfomEj1yCxZbRI/cgsZc0TO3oD2MRE/dgvaUFj13C1p8ET15C0cbwHr2Fp42gFPoSxvACfj1rAEcEiIva8gEPX9pIybo+UsbMEGPX954uabv4bR+uExl1/t3btPql0F4a7EhwGLc7HHZfDd7jfF7Wt+vTx/I4B0SdUF/Z1a8BYq3DRVa9cAhWtTpBw5v+bW+vcNwdhWGt4BX6y/EcvRGrqtvrzKcdYZ3XW6tv/8qOkO8621S8fpoQdHRe8tuUvaC9Ex2obI9qIDaV1RBO8vlgNbX/G2++VQsH4iIewREFWPo7tZPm1Nxfj6dNuf3dgi6d+NdvmslE24l9CX/sMZVGwzziDefbBLuI4wmFcRjgVdFsSWXKvJI0t9EOFTpmCMpqD0ijqSEOwhHd+ETR1LC/bKtwYfX4h9ew/7sEm6VbQ0+ulaPcAOAtxqAkz+5NoXfFp9c+o2yzE9O4E8usD+4oDaosvjcatgh57hP3TZ9jYM5hHBsO/o3vx7bncEY6vTUdgYP3C5h+cPiIXfVl1t4nPjyrZl0rSXbkapOj+1hOsBrbbkOB7f371qUba2o04Pb83ttrsPB3Y+ihjWIEgJ3HES8nYQOJ/fbGGpYQ0jPbU+/CsRfFfFADnFGkC9TXt0Qkz/PIZzUPYU4I8iXek7HEUT0B6d0P4IK0uFgX+oxPVrYoq2Q+hLn9NsYurUo3yDSczoOIqZDioWRfhQ5GokSVkaGYURrCnuHw7ofRrceZRtHTk/rYRwRLbo+3nHYb4r/rHfvnKcofKxoTtiYz6RKraaYVtzyyRFYjjMwJ6jVUM2pYTmlgTmNWg3VnBaV4zoDczq1GqY5voTltHxzvFOroZoDA9nNX3KRTw0M5KiGag4MZDd/9UY+NTCQoxqqOTCQXTAwBwayCxbm4EAWA3NwIIuBORUO5IpvToUDubIwBweyQUKucCBbJOQKB7JBQq5wIFsk5AoHskUmrWAiW4TACgayReqqYCBbxByBeWyRKwTmsUGsEJjGFqlCYBobhAqBWWyRKQRmsUGkEJjEFolC8LUKA2tgDlvkCcGDMd+agMdiA2sCjGGD5bYAY9gi2QQUwxbOoBQ2MQaFsMkARiFsAZqAMtjigXBbCZwVY5AibhuBi1qYxtQogQ2SZ43y1yJ41ih/DZZBa5S+FpOVGsWvweJ5jdLXYk5Zo/Q12HKpUfhaTP1rFL4GG3U1Cl+LFZoGha8ziFUNSl+TpbQGxa/FqmeD8tdk0bNBAWyxWt7A+dciczYogi12WRqUwSabLA0KYYvduQalsMnm3FW972F9fq+BYRB/r/p8CzKodvhlHQah96q6tyCDageMW4PA28K4tUi8LYxbg8jbwri1yLwtjFuD0NvCuLVIvR2aei1ONXZo6jU51NihqdfiNGyHpl6Tw7AdimGLU9QdimGTQ9QdvOxrkHo7FMPeIvV2KIa9QertUAx7g9RblfDe2/AdRXu1TFXCHBYDMQmVjUlhPJ8amMPzd/3kE4MXNuZfb5NPDczh+bcm5hOD1zXmXx6VTw3M4fn3AecTgx+BiNZMLqDMp0bNYaIYp8cw7x1olVNjmClGj+Hp/Rj51KgxzBSTgGHaBZgV3JsbrCGKScAw7eVHFdyaG6whiknA8CQO51OjxzBPDN6YG6zhBVC4MTdYQxSTgGFeAIX7coM1RDF6DPPyJ1yWi84QteghzEufcFEuGkPUokcwL3vCJbloDE8L3pCLxvCSJ1yQi8YQtejxy8udcDkuGkPUoocvL3XCxbhoDFGLHr68zAl34qIxRC16+PISJ1yIG5b1aFrwOtwQ8Xhi9OGXp0UPX17ahLtw0RiiFj18p28oyadGTV+mGD1+p+83z6dGzV+mGD2ACyL19PtxPDF4FW6whvekhKtwgzVEMXoIF7x0BVfhBmuIYhIwzEvkcBlusIYoJgHDvFkc3IYbrCGKScAwb+YP9+EGa3hi4D7cyBreahHciBusIYpJwDBvhRHuxA3WEMUkYJi4LA3X4kaZj6gmJQ/zMihcjRuZQ1STgGLiNhhcjxuZw1MD9+PG5vByKNyQG5lDVJOAY+K2O9yRG5lDVJMCZF4WhVtyI3OIalKAzEujcE9uZA5RTQqQeXkUbsqNzOGpaXEgx6PmEwJmO8Hcwvf1jM6aT0JgPjkJp4aJ5qRc9E40J+Gid6I5KI/HF70TzUm46J1oTspF70RzEi56J5qTctE7zxy4Sze66J1nDlymG1/0TjQn4aJ3ojkpF70TzUm46J1oDgzkUeebaE7CRe9Ec1Iueieak3DRO9GclIveaeYI3qpz/IQscKtufNE70ZyEi96J5qRc9E40J+Gid6I5OJANErLg3TpnkEkFLtcVBiFQ8HadQeoSuF1X8EOX4O06g8wlcLuu4Ecuwdt1BolL8PfS8QOX4O06g7wl+Fvp+HFL8HadRdrC30lnELbwdp1F1sLfSGcQtRTtOgNrFO+jM7AGz8QW1sAY5i9ECt6us8h8cL3OwhmUwibGwBevGRgDX7tmYQy8d8c3Bq7XWQAYrtcZPLXhep3FQxuu1xkkPbheZxH04HqdwewArtdZTA7gep3BjBKu11lMKOF6ncEqBFyvs1iEgOt1/A1Dget1FgtXcL2Ov80scL3OYn0Rbtc5g+gLt+tMFoLhdp3Fmj3crjNZsofbdRZ7PXC7zmSrB27XWewRwu06ky1CuF1nsLcscLvOZGv5ql239JoCoik1LoNqR7OswyD0XnXpFl9TQLQDxq1B4IVbdBZHnQRu0RmckRO4RWdxRE7gFp3B2UqBW3QWRysFL9EZpF64Q2dxJFfwCp1B6oUbdBZHuQUv0BmkXrg/Z1EBELw+Z5B64facRXVE9OU5pjXwmzYsUi9enTPIvnBzzlskYLg4N2pj0cq6Ahfn/Py71PKJwU8/RGtoJW+Ba3ODNUQx+tYc730SApfmBmuIYvDOXG8N730SAlfmojVMMXhjLlpDu4pE4MLcYA1RjB7DvIquwHW5wRqiGD2GedVuwV88FwzE6DHMuxJA8BfPBQMxCRimXSUh+IvngoGYBAzTriAR/MVzwUBMAoZ5ARR/8VwwEJOAYVoADXBFbrCGKCYBw7QAGuCC3GANUYwew7T8GeB2XHSGqEUPYVr6DHAzLhpD1KJHMC17BrgVF40hatEDmJY8A9yJi8YQtejxS8udAW7ERWOIWvTwpaXOAPfhojFELXr40jJngNtw0RiiloTVYJ4Y/WIwT0tC+qWJgZtwQ8LjadHDl5c24R5cNIaoRQ9f3vskAlyDGzadiGL0+OW9TyLAPbjRfhxPjB7AvPdJBLgJN1hDFKNHMO99EgHvwgUDMQmXWPLSFdyGG6whiknAMC+Rw324wRqimAQM82ZxcCNusIYoJgHDvJk/3IkbrCGKScAwb7UIbsUN1hDFJGCYt8II9+IGa4hiEjBMXJaGq3GjzEdUk5KHeRkUbseNzCGqSUAxbxsswP24kTlENQkw5m2fBrghNzKHqCblandeEoU7ciNziGpSgMzLonBLbmQOUU0KkHlpFH4L3cgcopoUIPPyKPweupE5RDUpQOYlUrhDNzKHqMa9/Ha32p43j5ev9WX3vDmetvvXr/f35vTU/1W79ZfN7vLr/9ocfnr66enTL8/ni9bzp+KTC59+fX48/rn++tfT6uXlf0NvfZs=

In game it looks like this: https://i.imgur.com/Zgwt1k3.jpg

Not a game-breaking bug, but still weird.

**Comment by demipixel** [comment]
God damnit.

**Comment by jziolkowski** [comment]
I'm on the latest .16 if that makes any difference

**Comment by demipixel** [comment]
It doesn't. I'll fix it soon.

**Comment by demipixel** [comment]
Should be fixed, please reopen if the problem persists!
