### ISSUE TITLE
Bug:  Output settings in Constant Combinators lost on flip

### ISSUE THREAD

**Issue by labrown** [demipixel/factorio-generators#24]
The output settings in constant Combinators are lost when you manipulate a blueprint.  In my case I flipped them around the horizontal axis and discovered the output settings for the constant combinators in the print were lost.

**Comment by demipixel** [comment]
I wonder if this is recent, since at least exporting constants has worked for a while (and I thought importing worked too). I'll look into it.

**Comment by labrown** [comment]
Dunno.  My first use of the site was just a couple days ago. Thanks for the prompt response.

**Comment by demipixel** [comment]
Should be fixed, please reopen if the problem persists.
