### ISSUE TITLE
Feature Request: change blueprint name in blueprintTool

### ISSUE THREAD

**Issue by EmperorArthur** [demipixel/factorio-generators#26]
I've found myself using blueprint tool to flip several blueprints.  However, it's somewhat confusing when the new blueprint has the same name as the old one.

A re-name option would be greatly appreciated, and shouldn't be that hard to implement.

**Comment by demipixel** [comment]
This can easily be done in this library by simply using `bp.name = 'Name here'`. Please reopen in the Autotorio repository is you're interested in having it there!
