### ISSUE TITLE
Blueprint tool can't handle filter inserters

### ISSUE THREAD

**Issue by ultravasili** [demipixel/factorio-generators#35]
Imported blueprints return "Unknown name:stack_filter_inserter;Unknown name:filter_inserter;"

**Comment by demipixel** [comment]
What's the blueprint?

**Comment by ultravasili** [comment]
https://pastebin.com/bkwiS1GC
Try mirroring it along any axis, it will be empty.

**Comment by demipixel** [comment]
Are you using the library or Autotorio?

**Comment by ultravasili** [comment]
Autotorio blueprint tool, this one. 
http://autotorio.com/blueprint?flipX=true&flipY=false&modifiedOnly=false
Importing in/out of latest vanilla 0.16.43.

**Comment by demipixel** [comment]
Fixed.

**Comment by ultravasili** [comment]
I think you broke it, I'm trying to mirror relatively large blueprint and it returns error
> Error: Expected name of entity or tile, instead got undefined

I was able to mirror much larger blueprints before: left side mirrored normally, right side returns error
https://i.imgur.com/iqAmhWF.jpg
Blueprint:
https://pastebin.com/ennzJfrQ

**Comment by demipixel** [comment]
Fixed.
