### ISSUE TITLE
Can't generator loading from both sides

### ISSUE THREAD

**Issue by dmurph** [demipixel/factorio-generators#43]
Wall blueprint string:
0eNqNj8EKwjAQRP9lzim0UWzNr4hIq4sspJvSpGop+XeT6kHQg8dZZt7OLOjsRMPIEmAW8NmJhzks8HyV1uZbmAeCAQfqoSBtn5UPTqi4t9YiKrBc6AFTxaMCSeDA9KKsYj7J1Hc0JsOvvMLgfIo4yd8SZlMqzDCF3saovhj6L0bxhmRGKrWWNx9bFW40+tW/a2qtm2pf1jrGJ+X9WWU=

Settings URL:
http://autotorio.com/outpost?modded=false&belt_type=fast&undergroundBelts=true&compact=false&trainSide=0&trainDirection=1&minerSpace=1&module=None&useStackInserters=true&useFilterInserters=false&includeRadar=true&includeLights=true&botBased=false&requestItem=Iron%20Ore&roboports=false&turretType=laser_turrets&walls=true&wallSpace=3&includeTrainStation=true&exitRoute=true&doubleLoading=true&locomotiveCount=1&cargoWagonCount=2

I wish I could copy the 'error'd string, I can fix it manually (light pole intersects with belt, easy to fix on my own). But it looks like it doesn't let me copy the result :(

**Comment by demipixel** [comment]
What's the size of the walls? Is it normal size or super small or something?

**Comment by dmurph** [comment]
I think just 1

**Comment by dmurph** [comment]
Which walls? The ones I have in the blueprint string? It's pretty large, definitely not very small.

**Comment by dmurph** [comment]
Here is what that looks like:
http://fbpviewer.trakos.pl/b/fHm7msoTLUxn6Tp-Wr2_tnPkTI4

The walls in the options I just have at thickness=1

**Comment by dmurph** [comment]
Exact error:
Error: Entity medium_electric_pole overlaps fast_transport_belt entity (68, 66)

**Comment by dmurph** [comment]
I also figured out how I can get it to work again - disabling the 'load from both sides' option. However, I need to load from both sides because it's a 2 car train :/

**Comment by gigajum** [comment]
I looked at the problem. The problem is the wall space value beeing 3, if you use 4 it works. Anyway here's the fix : #44

**Comment by demipixel** [comment]
Thanks, @gigajum , I'll have this on autotorio in a hot sec.

EDIT: Feel free to reopen if the issue persists
