### ISSUE TITLE
Feature Request: Request Chest Blueprint

### ISSUE THREAD

**Issue by WerFra** [demipixel/factorio-generators#48]
It would be nice if you could get a blueprint with a request chest requesting all required materials. This would be an easy way to collect all your material at your base and then head out to your outpost.

**Comment by demipixel** [comment]
What I could do it make a separate tool on Autotorio that gives you the requester chests for any blueprint. Would that be too inconvenient?

**Comment by WerFra** [comment]
That would work too. (And even better as it allows any blueprint) An extra button on the outpost generator to automatically fill in that blueprint would still be nice.

**Comment by WerFra** [comment]
I'm playing around with this, I will open a PR when im done. 
I currently can get the requester for a blueprint using the cli, but I already looked at the website and maybe add a PR there if I get through all that stuff. (First time really using JavaScript for something)

Small junction Blueprint that already works:
![image](https://user-images.githubusercontent.com/24651944/51062361-f5b61600-15f6-11e9-858d-eb3f8e030d18.png)

**Comment by demipixel** [comment]
Looks awesome! Although seems like you're starting from index 1 rather than 0 ;P

I think the tricky part here is splitting it up into multiple requester chests if needed.

**Comment by WerFra** [comment]
Got all that stuff in the PR, was too excited to get it running I used the screenshot I had ;)

![image](https://user-images.githubusercontent.com/24651944/51064056-13d34480-15fe-11e9-9e8b-fcc054365383.png)
![image](https://user-images.githubusercontent.com/24651944/51064062-1cc41600-15fe-11e9-9dd2-71fa7b424bf7.png)

**Comment by WerFra** [comment]
I'm not splitting if the request for one Item gets too large, but that is pretty much impossible as mods change stack sizes.

**Comment by demipixel** [comment]
Fair enough. I made some tiny adjustments, but seems like all that's left is implementation into Autotorio. Unless you want to, I can start that tool.
