### ISSUE TITLE
Misaligned splitters on outpost blueprint

### ISSUE THREAD

**Issue by msvisser** [demipixel/factorio-generators#5]
Hi,

I was using your tool through the website (autotorio.com) and I stumbled onto a bug. When I generated my outpost the splitters were misaligned with the belts that were generated. I have included some images to show the bug.

![Screenshot of the whole outpost](https://webmichiel.nl/screenshot/big.png)
![Screenshot of the splitters](https://webmichiel.nl/screenshot/small.png)

When generating the blueprint I used the following settings:

__Input blueprint:__
```0eNqNj8EKwjAQRP9lziu0NRbNr4hIq4sE0k1pUrWU/LtJvAh68LTMMvN2dkVvZx4nIwF6hbk48dDHFd7cpLN5F5aRoWECDyBIN2TlgxPePDprEQlGrvyEruOJwBJMMPymFLGcZR56npLhV54wOp8iTvK1hNnUFWHJU8VIX5DmL8ihIDIhdSrd9cerhDtPvrhbpZpd3ap9tY3xBYgcWS4=```
__Belt type:__ Fast Transport Belt
__Use underground belts:__ No
__Train station side:__ Left
__Train enter from:__ Bottom
__Miner space:__ 0
__Modules:__ None
__Use stack inserters:__ Yes
__Include radar:__ No
__Balancer blueprint string:__ Not provided
__Bot based:__ No
__Turret type:__ Laser Turrets
__Turret spacing:__ 8 (Field was actually empty)
__Walls enabled:__ Yes
__Wall thickness:__ 1 (Field was actually empty)
__Wall space:__ 5 (Field was actually empty)
__Include train station:__ Yes
__Provide exit route:__ No
__Locomotive count:__ 1
__Cargo wagon count:__ 2
__Tiles:__ All none

The generated output blueprint string can be found [here](https://gist.github.com/msvisser/387d7b58b5ada1ef2e26da2417556474), as it was too long to post in this issue.

I hope this will help you solve the issue, as I would love to see it working correctly, because I think the concept is awesome!

\- Michiel Visser

**Comment by demipixel** [comment]
same as https://github.com/demipixel/factorio-blueprint/issues/14

Issue seems to be related to 2 cargo wagons (not exactly that but that's the main problem).

**Comment by demipixel** [comment]
Resolved. Thanks for giving such a detailed report! Next time, though, I recommend just giving the settings URL and then you don't have to type them all out.
