### ISSUE TITLE
Can't use it with AAI industry (Error: Error loading blueprint)

### ISSUE THREAD

**Issue by IIPoliII** [demipixel/factorio-generators#51]
Hello,
I am trying to use this generator for my modded game but everytime i load my blue print an error is thrown out saying 
```
Error: Error loading blueprint: concrete_wall does not exist! You can add it by putting it into entityData.
```

Here is my BP 
```
0eNqNj0EKwjAQRe/y1yk06aKSq4hIrYMMpNOSpGopubtJ3AgiuPzDmzfzd1zcSotnibA7eJwlwB53BL7J4MosbgvBgiNNUJBhKilzo6dIzWNwDkmB5UpPWJ1OCiSRI9NbVMN2lnW6kM/AD4XCMoe8NUu5mU0mkxtsY3RK6ktj/tU0xlRP0eTXagv7UVrhTj5Uvu9a3etOt+0hpRdzM1zJ
```

And as you can see on this pics the walls exsists
![image](https://user-images.githubusercontent.com/29628512/58009598-16cfcb80-7aef-11e9-83d4-48c4ec06557e.png)

**Comment by gigajum** [comment]
The vanilla entity is called stone-wall.
Modded entites are not supported at this time, so you need to use the vanilla entity in the blueprint.

**Comment by IIPoliII** [comment]
Yes but any ideas how I could avoid that with a mod? I mean if I remove the mod now all my walls will be removed

**Comment by gigajum** [comment]
You can use a site like https://factorio.tmin10.ru/ and replace the string for the entity manually, which is a bit annoying.

**Comment by IIPoliII** [comment]
I will try that thanks for your help
