### ISSUE TITLE
Issue: landfill for curved rails is broken

### ISSUE THREAD

**Issue by JesseyWhite** [demipixel/factorio-generators#54]
When you use the landfill option in autotorio.com the resulting string does not correctly put landfill under all the curved rail correctly and when you import the string, two errors pop up.

Error while importing string:
Unknown item name: straight-rail
Unknown item name: curved-rail

**Comment by DidierLoiseau** [comment]
I also confirm the issue with Factorio 1.0. In fact, it does not matter if you select “_Landfill under entities_”.

Without any option selected, the output string is not the same as the original one – I don't know if this is intended.

If you select Landfill + “_Return modified only_”, it generates an empty blueprint.

**Comment by bplein** [comment]
I ran into this today, I'm trying to upgrade all my rail BPs to have landfill underneath. Factorio 1.0 as well.

**Comment by demipixel** [comment]
Champ, thank's for fixing this @chriswa !
