### ISSUE TITLE
Excessive heights for outposts

### ISSUE THREAD

**Issue by emmachase** [demipixel/factorio-generators#57]
Setting the --trainDirection flag to `0` and `3` result in an excessively large outpost generated, as illustrated in the following picture:
![](https://its-em.ma/and-her-rotten-space.png)

I've tracked this down to the following expression used when calculating the blueprint width/height in multiple places: `Math.min(INCLUDE_RADAR ? -3 : 0, _____)`. This expression can be found in a number of places, such as [here](https://github.com/demipixel/factorio-generators/blob/eb2416d04911ed64fd164e1696450ec62a26af83/tools/oilOutpost.js#L315), and [here](https://github.com/demipixel/factorio-generators/blob/eb2416d04911ed64fd164e1696450ec62a26af83/tools/lib/trainStation.js#L45); it's used more often than that, but those are the two main culprits as far as I can tell.

Removing these expressions fixes the issue but I'm sure that it probably introduces some other bugs, and I'm not sure exactly how to rewrite the expression to be correct.

**Comment by demipixel** [comment]
Would you be able to provide the input blueprint along with the options you used?

**Comment by emmachase** [comment]
Certainly, the input blueprint is ```0eNqV0u9OxCAMAPB36WfOyMafjVcxxux25KxujAAzLgvvLruZadyi+IlCyq9N0xnO3aitQxNAzYDtYDyohxk8Xk3TLW9hshoUYNA9EDBNv9zs2NuXpn2FSADNRb+DovGRgDYBA+rVuF2mJzP2Z+1SwvbbB9fg9Tmc0tEl1A4+/RrMUi5JJ8pFTWBaIlGmChd0ul0Tikh2cLFv68is6B3/VHkK/3bLTJdvLqt+uuLAZXmurH9xj/rl/54D4zmuyHTZl8ty5iAz3WJzS7bvN23dbTfVt1Um8KadXxMqyiSrpZD0XnAR4weXpe/c```

And I obtained the output referenced in the picture with the following:
```./cli <bp> --oil --cargoWagonCount 4 --exitRoute true --trainDirection 3 --trainSide 0```

**Comment by demipixel** [comment]
It seems like it's not centered. I haven't been able to test it but would you be able to try out:

https://github.com/demipixel/factorio-generators/tree/fix-57

and see if that works for you? I think it just kinda assumes that the blueprint is centered around 0,0 and so when it was centered around something like 1000,0 it made a wall ~1000+ long.

**Comment by demipixel** [comment]
Well over a year later, but the fix should be out now.
