### ISSUE TITLE
Error: Entity pipe overlaps pipe entity (777, -1157)

### ISSUE THREAD

**Issue by DidierLoiseau** [demipixel/factorio-generators#58]
This error happens in the Oil Outpost Generator, when 2 pumpjacks output in the same tile.

Blueprint string:
```
0eNqN0FEOwiAMANC79BuNzDEmVzHGbLPR6sYIMOOycHeZi0adH35BS/tKOkBZd2gsaQ9qAKpa7UBtB3B01EU95nxvEBSQxwYY6KIZI9M15lxUFwgMSB/wBoqHHQPUnjzhZDyCfq+7pkQbC17dztuCjie/iEcdUdO62NXqcVyUZB5Le1ALzjMeBxzIYjW9J4HN3GT+qzkp86V4oiLeP9n0B7v+ixVvrPhmk3Elj8Wptz0zuKJ1U0HOU5luZCb5KhNZCHe2MIDa
```
Rotating or removing one of the pumpjacks solves the problem, but the error is not very clear.

**Comment by demipixel** [comment]
Odd, are you using [Autotorio](https://autotorio.com/oil)? If so, are there any settings that cause the error? Putting that blueprint string in alone doesn't cause any error.

**Comment by DidierLoiseau** [comment]
Oh, yes, indeed, you need to include beacons to get the error. These settings allow to reproduce it:

https://autotorio.com/oil?modded=false&trainSide=1&trainDirection=2&module=Productivity%20Module%203&includeRadar=false&includeLights=false&beacons=true&turretType=none&walls=false&includeTrainStation=false&exitRoute=true

**Comment by demipixel** [comment]
Could you test it now?

**Comment by DidierLoiseau** [comment]
I confirm this is working now. Sorry I forgot to reply 😇
