### ISSUE TITLE
Power poles don't generate lines between them

### ISSUE THREAD

**Issue by matt-sorenson** [demipixel/factorio-generators#66]
I'm using [this](https://autotorio.com/outpost?modded=false&belt_type=express&undergroundBelts=true&compact=true&trainSide=3&trainDirection=2&minerSpace=0&module=Productivity%20Module%203&useStackInserters=true&useFilterInserters=false&includeRadar=false&includeLights=false&botBased=false&requestItem=Iron%20Ore&roboports=false&turretType=none&walls=false&includeTrainStation=false&exitRoute=true&doubleLoading=true) setting to generate my outposts but the power poles don't have lines between them when I put the blueprint into the game.

I'm on 1.1.35-1

**Comment by demipixel** [comment]
Fixed!
