### ISSUE TITLE
Avoid landfill for walls

### ISSUE THREAD

**Issue by EmileSonneveld** [demipixel/factorio-generators#72]
Water is better at blocking biters than walls.
I propose to not add landfill for walls when using the `LANDFILL_ENTITIES` option, as it could make outposts weaker.

Pull request in a moment...

**Comment by EmileSonneveld** [comment]
Made PR. Should this be behind an option? For if walls are used for aesthetics

**Comment by demipixel** [comment]
Seems reasonable enough to me. Can add an option if somebody complains.
